<a href="https://colab.research.google.com/github/divyasri0331/python/blob/main/day%2035.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
import warnings
warnings.filterwarnings('ignore')

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [7]:
titanic = pd.read_csv("/content/titanic (1).csv")
titanic.head()

  Class Gender    Age Survived
0   3rd   Male  Child       No
1   3rd   Male  Child       No
2   3rd   Male  Child       No
3   3rd   Male  Child       No
4   3rd   Male  Child       No

In [8]:
titanic['Class'].unique()

array(['3rd', '1st', '2nd', 'Crew'], dtype=object)

In [9]:
titanic['Class'].value_counts()

Class
Crew    885
3rd     706
1st     325
2nd     285
Name: count, dtype: int64

In [10]:
titanic['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [11]:
titanic['Gender'].value_counts()

Gender
Male      1731
Female     470
Name: count, dtype: int64

In [12]:
titanic['Age'].unique()

array(['Child', 'Adult'], dtype=object)

In [ ]:
titanic['Age'].value_counts()

In [13]:
titanic['Survived'].unique()

array(['No', 'Yes'], dtype=object)

In [14]:
titanic['Survived'].value_counts()

Survived
No     1490
Yes     711
Name: count, dtype: int64

In [15]:
df=pd.get_dummies(titanic,dtype='int')
df.head()

,Class_1st,Class_2nd,Class_3rd,Class_Crew,Gender_Female,Gender_Male,Age_Adult,Age_Child,Survived_No,Survived_Yes
0,0,0,1,0,0,1,0,1,1,0
1,0,0,1,0,0,1,0,1,1,0
2,0,0,1,0,0,1,0,1,1,0
3,0,0,1,0,0,1,0,1,1,0
4,0,0,1,0,0,1,0,1,1,0

APRIORI ALGORITHM

In [17]:
frequent_itemsets = apriori(df, min_support=0.1, use_colnames=True)
frequent_itemsets

     support                                           itemsets
0   0.147660                                        (Class_1st)
1   0.129487                                        (Class_2nd)
2   0.320763                                        (Class_3rd)
3   0.402090                                       (Class_Crew)
4   0.213539                                    (Gender_Female)
5   0.786461                                      (Gender_Male)
6   0.950477                                        (Age_Adult)
7   0.676965                                      (Survived_No)
8   0.323035                                     (Survived_Yes)
9   0.144934                             (Class_1st, Age_Adult)
10  0.118582                             (Age_Adult, Class_2nd)
11  0.231713                           (Gender_Male, Class_3rd)
12  0.284871                             (Class_3rd, Age_Adult)
13  0.239891                           (Survived_No, Class_3rd)
14  0.391640                          (Gender_Male, Class_Crew)
15  0.402090                            (Class_Crew, Age_Adult)
16  0.305770                          (Class_Crew, Survived_No)
17  0.193094                         (Gender_Female, Age_Adult)
18  0.156293                      (Survived_Yes, Gender_Female)
19  0.757383                           (Gender_Male, Age_Adult)
20  0.619718                         (Gender_Male, Survived_No)
21  0.166742                        (Gender_Male, Survived_Yes)
22  0.653339                           (Survived_No, Age_Adult)
23  0.297138                          (Survived_Yes, Age_Adult)
24  0.209905                (Gender_Male, Class_3rd, Age_Adult)
25  0.191731              (Gender_Male, Survived_No, Class_3rd)
26  0.216265                (Survived_No, Class_3rd, Age_Adult)
27  0.391640               (Gender_Male, Class_Crew, Age_Adult)
28  0.304407             (Gender_Male, Class_Crew, Survived_No)
29  0.305770               (Class_Crew, Survived_No, Age_Adult)
30  0.143571           (Survived_Yes, Gender_Female, Age_Adult)
31  0.603816              (Gender_Male, Survived_No, Age_Adult)
32  0.153567             (Gender_Male, Survived_Yes, Age_Adult)
33  0.175829   (Gender_Male, Survived_No, Class_3rd, Age_Adult)
34  0.304407  (Gender_Male, Class_Crew, Survived_No, Age_Adult)

In [18]:
rules=association_rules(frequent_itemsets,metric='lift',min_threshold=0.7)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Class_1st),(Age_Adult),0.147660,0.950477,0.144934,0.981538,1.032680,1.0,0.004587,2.682493,0.037128,0.152050,0.627212,0.567012
1,(Age_Adult),(Class_1st),0.950477,0.147660,0.144934,0.152486,1.032680,1.0,0.004587,1.005694,0.639010,0.152050,0.005661,0.567012
2,(Age_Adult),(Class_2nd),0.950477,0.129487,0.118582,0.124761,0.963505,1.0,-0.004492,0.994601,-0.433377,0.123346,-0.005429,0.520275
3,(Class_2nd),(Age_Adult),0.129487,0.950477,0.118582,0.915789,0.963505,1.0,-0.004492,0.588085,-0.041697,0.123346,-0.700435,0.520275
4,(Gender_Male),(Class_3rd),0.786461,0.320763,0.231713,0.294627,0.918520,1.0,-0.020555,0.962947,-0.293496,0.264660,-0.038478,0.508503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,"(Survived_No, Age_Adult)","(Gender_Male, Class_Crew)",0.653339,0.391640,0.304407,0.465925,1.189676,1.0,0.048533,1.139090,0.459917,0.411043,0.122107,0.621594
102,(Gender_Male),"(Class_Crew, Survived_No, Age_Adult)",0.786461,0.305770,0.304407,0.387060,1.265851,1.0,0.063931,1.132622,0.983509,0.386390,0.117093,0.691301
103,(Class_Crew),"(Gender_Male, Survived_No, Age_Adult)",0.402090,0.603816,0.304407,0.757062,1.253795,1.0,0.061619,1.630802,0.338549,0.433938,0.386805,0.630600
104,(Survived_No),"(Gender_Male, Class_Crew, Age_Adult)",0.676965,0.391640,0.304407,0.449664,1.148157,1.0,0.039280,1.105434,0.399458,0.398335,0.095378,0.613463
105,(Age_Adult),"(Gender_Male, Class_Crew, Survived_No)",0.950477,0.304407,0.304407,0.320268,1.052103,1.0,0.015075,1.023334,1.000000,0.320268,0.022802,0.660134